main: com.stardevllc.starhomes.StarHomesPlugin
version: ${version}
api-version: 1.13
name: ${rootProject.name}
author: Firestar311
depend: [StarCore]
softdepend: [PlaceholderAPI]
commands:
  delhome: 
  home: 
  renamehome:
  sethome: